### ISSUE TITLE
flickr30k model download is pointing to coco model.

### ISSUE THREAD

**Issue by volkancirik** [jiasenlu/NeuralBabyTalk#5]
[the link to flickr30k](https://github.com/jiasenlu/NeuralBabyTalk/blame/master/README.md#L46) is pointing to coco model. Do you mind updating the link?

**Comment by jiasenlu** [comment]
Thanks the link is 

https://www.dropbox.com/s/cirzj1b2jul6yzx/flickr30k_nbt_1024.tar.gz?dl=0

will update now.
