### ISSUE TITLE
where do you truncate captions to 16 words

### ISSUE THREAD

**Issue by volkancirik** [jiasenlu/NeuralBabyTalk#7]
Hello,

In the paper you say, "We truncate captions longer than 16 words for both COCO and Flickr30k Entities
dataset", but I could not find where you did that in scripts under `prepro/`. For [ngrams](https://github.com/jiasenlu/NeuralBabyTalk/blob/01b4dfccea9c2177b59a79e7110273dcc516a166/prepro/prepro_ngrams_flickr30k.py#L89) you define `seq_length` but never use it. Similarly,  for [dictionary script](https://github.com/jiasenlu/NeuralBabyTalk/blob/01b4dfccea9c2177b59a79e7110273dcc516a166/prepro/prepro_dic_flickr.py#L184) you do not use max_length parameter in the rest of the script. 

Am I looking at the wrong scripts? Do you mind clarifying? Thanks!

**Comment by jiasenlu** [comment]
There is a seq_lenght option in the main script. You can check here. 

https://github.com/jiasenlu/NeuralBabyTalk/blob/master/opts.py#L70

by setting this option to 16, I think you can truncate the caption.

**Comment by volkancirik** [comment]
Thanks!

How do you handle when the reference caption is longer than 16 words during evaluation? Do you ignore that instance? or truncate reference to 16 tokens as well?

**Comment by jiasenlu** [comment]
no, during evaluation, the ground truth caption is directly loading from the evaluation file. However, the generated caption will still remain in seq_length you set. 

check this function for more details. 

https://github.com/jiasenlu/NeuralBabyTalk/blob/master/misc/utils.py#L320

**Comment by volkancirik** [comment]
thanks for the explanation!
