### ISSUE TITLE
Cannot find _roi_align?

### ISSUE THREAD

**Issue by xmengli999** [jiasenlu/NeuralBabyTalk#8]
I run the inference code and has an error:

ImportError: No module named _roi_align
It appears that " from ._roi_align import lib as _lib, ffi as _ffi" can not be found.

Is there any code missing?

**Comment by xmengli999** [comment]
I solved this issue by run make.sh in the roi_align folder. 

However, the modules.roi_crop still cannot be found?
# from pooling.roi_crop.modules.roi_crop import _RoICrop

**Comment by linhai-meng** [comment]
from pooling.roi_crop.modules.roi_crop import _RoICrop  ,Is there the modules missing? I also have the question.

**Comment by jiasenlu** [comment]
Hi, since we are not using roi crop in the model, you can simply delete the import. I just update the code.

**Comment by zzw1123** [comment]
Have you solved the problem? @xmengli999

**Comment by xmengli999** [comment]
@zzw1123 
Yes. Just remove this import.

**Comment by xmengli999** [comment]
@zzw1123  which error?

**Comment by zzw1123** [comment]
This one:
'''
from ._roi_align import lib as _lib, ffi as _ffi
ImportError: No module named _roi_align
'''

**Comment by xmengli999** [comment]
@zzw1123 I solved this issue by run make.sh in the roi_align folder.
Try to see if you make it correctly.
